version: "3.9"
services:

  # gurobi-compute with wls-license
  compute:
    container_name: gurobi-compute
    image: gurobi/compute:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    configs:
      - source: compute_config
        target: /opt/gurobi/gurobi.lic
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg14
    #command: postgres -c 'max_connections=500' -B 4096MB
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dmas
      - TS_TUNE_MAX_CONNS=2000
    ports:
      - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    container_name: dmas-grafana
    user: "104"
    depends_on:
      - simulationdb
    ports:
      - 3001:3000
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard-definitions:/etc/grafana/provisioning/dashboard-definitions
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  controller:
    container_name: ctl
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    build: .
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'CTL'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  market:
    container_name: mrk
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'MRK'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'
    configs:
      - source: market_config
        target: /opt/gurobi/gurobi.lic


  tso:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'NET'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  dem_de111:
    container_name: dem_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'DEM'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  dem_de112:
    container_name: dem_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'DEM'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  pwp_de111:
    container_name: pwp_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'PWP'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  pwp_de112:
    container_name: pwp_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'PWP'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  res_de111:
    container_name: res_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'RES'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'

  res_de112:
    container_name: res_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'RES'
      MQTT_HOST: 'rabbitmq'
      SIMULATION_SOURCE: 'simulationdb:5432'
configs:
  compute_config:
    file: ./gurobi.lic

  market_config:
    file: ./market_gurobi.lic
