version: "3"
services:

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dMAS
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: nowum-energy@fh-aachen.de
        PGADMIN_DEFAULT_PASSWORD: nowum
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 9090:80

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  market:
    container_name: ctl
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'CTL'
      CONNECT: 'True'

  market:
    container_name: mrk
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'MRK'
      CONNECT: 'True'

  weather:
    container_name: wtr
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'WTR'
      CONNECT: 'True'

  tso:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'NET'
      CONNECT: 'True'

  dem50:
    container_name: dem50
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 50
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem51:
    container_name: dem51
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 51
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem52:
    container_name: dem52
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 52
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem53:
    container_name: dem53
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 53
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem54:
    container_name: dem54
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 54
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem55:
    container_name: dem55
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 55
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  pwp50:
    container_name: pwp50
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 50
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp51:
    container_name: pwp51
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 51
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp52:
    container_name: pwp52
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 52
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp53:
    container_name: pwp53
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 53
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp54:
    container_name: pwp54
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 54
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp55:
    container_name: pwp55
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 55
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  res50:
    container_name: res50
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 50
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res51:
    container_name: res51
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 51
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res52:
    container_name: res52
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 52
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res53:
    container_name: res53
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 53
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res54:
    container_name: res54
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 54
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res55:
    container_name: res55
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 55
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      