version: "3.9"
services:

  # gurobi-compute with wls-license
  compute:
    container_name: gurobi-compute
    image: gurobi/compute:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    configs:
      - source: compute_config
        target: /opt/gurobi/gurobi.lic
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg14
    #command: postgres -c 'max_connections=500' -B 4096MB
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dmas
      - TS_TUNE_MAX_CONNS=500
    ports:
      - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    container_name: dmas-grafana
    user: "104"
    depends_on:
      - simulationdb
    ports:
      - 3001:3000
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_INSTALL_PLUGINS: volkovlabs-echarts-panel
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard-definitions:/etc/grafana/provisioning/dashboard-definitions
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


  controller:
    container_name: controller
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    build: .
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'CTL'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: '0.0.0.0'
    ports:
      - 5000:5000
      - 4000:4000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - simulationdb

  market:
    container_name: market
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'MRK'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
    configs:
      - source: market_config
        target: /opt/gurobi/gurobi.lic
    depends_on:
      - controller


  net:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'NET'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
    depends_on:
      - controller

  dem:
    container_name: dem
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'DEM'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
    depends_on:
      - controller

  pwp_de5:
    container_name: pwp_de5
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE5
      TYPE: 'PWP'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
      STRUCTURE_SERVER: '10.13.10.41:5432'

  res_de5:
    container_name: res_de5
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE5
      TYPE: 'RES'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
      STRUCTURE_SERVER: '10.13.10.41:5432'
    depends_on:
      - controller

  str_ded:
    container_name: str_ded
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DED
      TYPE: 'STR'
      SIMULATION_SOURCE: 'simulationdb:5432'
      WS_HOST: 'controller'
      STRUCTURE_SERVER: '10.13.10.41:5432'
    depends_on:
      - controller
configs:
  compute_config:
    file: ./gurobi.lic

  market_config:
    file: ./market_gurobi.lic
