version: "3"
services:

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg12
    command: postgres -c 'max_connections=500' -B 4096MB
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dmas
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  controller:
    container_name: ctl
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'CTL'
    ports:
      - 5000:5000

  market:
    container_name: mrk
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'MRK'
    volumes:
    - ./gurobi.lic:/opt/gurobi/gurobi.lic:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  tso:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: 'DE111'
      TYPE: 'NET'

  dem_de111:
    container_name: dem_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'DEM'
      
  dem_de112:
    container_name: dem_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'DEM'
      
  dem_de113:
    container_name: dem_de113
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE113
      TYPE: 'DEM'
      
  dem_de114:
    container_name: dem_de114
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE114
      TYPE: 'DEM'
      
  dem_de115:
    container_name: dem_de115
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE115
      TYPE: 'DEM'
      
  pwp_de111:
    container_name: pwp_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'PWP'
      
  pwp_de112:
    container_name: pwp_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'PWP'
      
  pwp_de113:
    container_name: pwp_de113
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE113
      TYPE: 'PWP'
      
  pwp_de114:
    container_name: pwp_de114
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE114
      TYPE: 'PWP'
      
  pwp_de116:
    container_name: pwp_de116
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE116
      TYPE: 'PWP'
      
  res_de111:
    container_name: res_de111
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE111
      TYPE: 'RES'
      
  res_de112:
    container_name: res_de112
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE112
      TYPE: 'RES'
      
  res_de113:
    container_name: res_de113
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE113
      TYPE: 'RES'
      
  res_de114:
    container_name: res_de114
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE114
      TYPE: 'RES'
      
  res_de115:
    container_name: res_de115
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      AREA_CODE: DE115
      TYPE: 'RES'
      