version: "3"
services:

  mongodb:
    container_name: mongodb
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/sch-pg:/var/lib/postgresql/data

  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin
      DOCKER_INFLUXDB_INIT_ORG: dmas

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - 15672:15672

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000





