version: "3"
services:

  agent:
    container_name: agent_x
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gurobi_wls.lic:/opt/gurobi/gurobi_wls.lic:ro

