version: "3"
services:

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dMAS
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: nowum-energy@fh-aachen.de
        PGADMIN_DEFAULT_PASSWORD: nowum
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 9090:80

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  controller:
    container_name: ctl
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'CTL'
      CONNECT: 'True'
    ports:
      - 5000:5000

  market:
    container_name: mrk
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'MRK'
      CONNECT: 'True'

  weather:
    container_name: wtr
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'WTR'
      CONNECT: 'True'

  tso:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'NET'
      CONNECT: 'True'

  dem780:
    container_name: dem780
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 780
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem781:
    container_name: dem781
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 781
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem782:
    container_name: dem782
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 782
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem783:
    container_name: dem783
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 783
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem784:
    container_name: dem784
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 784
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem785:
    container_name: dem785
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 785
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem786:
    container_name: dem786
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 786
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem787:
    container_name: dem787
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 787
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem790:
    container_name: dem790
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 790
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem791:
    container_name: dem791
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 791
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem792:
    container_name: dem792
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 792
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem793:
    container_name: dem793
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 793
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem794:
    container_name: dem794
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 794
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem795:
    container_name: dem795
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 795
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem796:
    container_name: dem796
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 796
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem797:
    container_name: dem797
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 797
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem798:
    container_name: dem798
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 798
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem803:
    container_name: dem803
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 803
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem804:
    container_name: dem804
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 804
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  dem805:
    container_name: dem805
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 805
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  pwp10:
    container_name: pwp10
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 10
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp11:
    container_name: pwp11
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 11
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp14:
    container_name: pwp14
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 14
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp19:
    container_name: pwp19
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 19
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp29:
    container_name: pwp29
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 29
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp30:
    container_name: pwp30
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 30
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp31:
    container_name: pwp31
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 31
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp41:
    container_name: pwp41
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 41
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp45:
    container_name: pwp45
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 45
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp46:
    container_name: pwp46
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 46
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp48:
    container_name: pwp48
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 48
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp61:
    container_name: pwp61
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 61
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp62:
    container_name: pwp62
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 62
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp63:
    container_name: pwp63
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 63
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  pwp64:
    container_name: pwp64
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 64
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      
  res794:
    container_name: res794
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 794
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res795:
    container_name: res795
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 795
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res796:
    container_name: res796
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 796
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res797:
    container_name: res797
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 797
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res798:
    container_name: res798
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 798
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res803:
    container_name: res803
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 803
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res804:
    container_name: res804
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 804
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res805:
    container_name: res805
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 805
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res806:
    container_name: res806
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 806
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res808:
    container_name: res808
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 808
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res809:
    container_name: res809
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 809
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res812:
    container_name: res812
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 812
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res813:
    container_name: res813
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 813
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res814:
    container_name: res814
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 814
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res815:
    container_name: res815
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 815
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res816:
    container_name: res816
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 816
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res817:
    container_name: res817
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 817
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res818:
    container_name: res818
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 818
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res819:
    container_name: res819
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 819
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      
  res820:
    container_name: res820
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 820
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      