version: "3"
services:

  dwd1:
    container_name: dwd1
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
        START_DATE: 199501
        END_DATE: 199501

  dwd2:
    container_name: dwd2
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
        START_DATE: 199502
        END_DATE: 199502

  dwd3:
    container_name: dwd3
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
        START_DATE: 199503
        END_DATE: 199503

  dwd4:
    container_name: dwd4
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199504
      END_DATE: 199504

  dwd5:
    container_name: dwd5
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199505
      END_DATE: 199505

  dwd6:
    container_name: dwd6
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199506
      END_DATE: 199506

  dwd7:
    container_name: dwd7
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199507
      END_DATE: 199507

  dwd8:
    container_name: dwd8
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199508
      END_DATE: 199508

  dwd9:
    container_name: dwd9
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199509
      END_DATE: 199509

  dwd10:
    container_name: dwd10
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199510
      END_DATE: 199510

  dwd11:
    container_name: dwd11
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199511
      END_DATE: 199511

  dwd12:
    container_name: dwd12
    image: dwd_crawler:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_dwd
    environment:
      START_DATE: 199512
      END_DATE: 199512