version: "3"
services:

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=dMAS
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: nowum-energy@fh-aachen.de
        PGADMIN_DEFAULT_PASSWORD: nowum
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 9090:80

  gurobi:
    image: gurobi/compute:latest
    container_name: gurobi_compute
    ports:
        - 61000:61000
    command: --hostname=149.201.195.139
    volumes:
      - ./gurobi_wls.lic:/opt/gurobi/gurobi.lic:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  controller:
    container_name: ctl
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'CTL'
      CONNECT: 'True'
    ports:
      - 5000:5000

  market:
    container_name: mrk
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'MRK'
      CONNECT: 'True'
      COMPUTE_SERVER: '149.201.195.139:61000'

  weather:
    container_name: wtr
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'WTR'
      CONNECT: 'True'

  tso:
    container_name: net
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 1
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'NET'
      CONNECT: 'True'

  dem780:
    container_name: dem780
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 780
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'DEM'
      CONNECT: 'True'
      
  pwp10:
    container_name: pwp10
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 10
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'PWP'
      CONNECT: 'True'
      COMPUTE_SERVER: '149.201.195.139:61000'
      
  res794:
    container_name: res794
    image: registry.git.fh-aachen.de/nowum-energy/projects/dmas/agent:latest
    environment:
      PLZ_CODE: 794
      MQTT_EXCHANGE: 'dMAS'
      AGENT_TYPE: 'RES'
      CONNECT: 'True'
      