version: "3"
services:

  simulationdb:
    container_name: simulationdb
    image: timescale/timescaledb:latest-pg12
    command: postgres -c 'max_connections=500' -B 4096MB
    restart: always
    environment:
      - POSTGRES_USER=dMAS
      - POSTGRES_PASSWORD=dMAS
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nowum-energy@fh-aachen.de
      PGADMIN_DEFAULT_PASSWORD: nowum
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 9090:80

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

