# run: conda env create -f environment.yml
# or to recreate: conda env create -f environment.yml --force
name: dmas
dependencies:
- python=3.11
- numpy
- pandas
- matplotlib
- Flask
- SQLAlchemy
- pip
- pip:
  - -r requirements.txt
- pytest-cov
