{
 "title": "DMAS",
 "description": "Dashboard of the distributed Multi-Agent-Simulation",
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "2018-01-31T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "agent",
    "query": "Select distinct agent from capacities"
   }
  ]
 },
 "panels": [
  { "title": "Market Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weather Explorer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air\",\n  avg(ghi) AS \"ghi\"\nFROM cosmo\nWHERE\n  $__timeFilter(\"time\") AND\n  country = 'DE'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(SQRT(POWER(wind_meridional,2)+POWER(wind_zonal,2))) AS \"wind_speed\"\nFROM cosmo\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(nuclear) + sum(coal) +  sum(water) + sum(bio) + sum(gas) + sum(lignite) + sum(wind) + sum(solar) as \"total\"\nFROM capacities\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Installed Capacity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(bio) AS \"bio\",\n  sum(wind) AS \"wind\",\n  sum(solar) AS \"solar\",\n  sum(coal) AS \"coal\",\n  sum(lignite) AS \"lignite\",\n  sum(gas) AS \"gas\",\n  sum(water) AS \"water\",\n  sum(storage) AS \"storage\",\n  sum(nuclear) AS \"nuclear\"\nFROM capacities\nWHERE\n  $__timeFilter(\"time\") AND\n  agent NOT LIKE 'dem_de%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Market Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  price*1000 AS \"price\",\n  avg(price*1000) OVER (ORDER BY \"time\" ROWS 5 PRECEDING) AS \"price_mean\"\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Market Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(dem.time,1h),\n  sum(dem.power) - sum(gen.solar) as \"demand\"\nFROM demand dem\nJOIN generation gen on gen.agent = dem.agent and $__timeFilter(dem.time) \n  and time_bucket('1h', dem.time) = time_bucket('1h', gen.time)\nWHERE dem.step = 'post_dayAhead' and gen.step = 'post_dayAhead' and dem.agent LIKE '%dem%' \n  \nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(volume) AS \"market volume\",\n  sum(magic_source) as \"magic source\"\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(nuclear) + sum(coal) + sum(lignite) + sum(gas) as \"fossil energy\",\n  sum(water) + sum(bio) + sum(lignite) + sum(wind) +  sum(solar) AS \"renewable energy\"\nFROM generation\nWHERE\n  $__timeFilter(\"time\") AND\n  step = 'post_dayAhead' AND\n  agent not like '%dem%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Generation Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(nuclear) AS \"nuclear\",\n  sum(coal) AS \"coal\",\n  sum(water) AS \"water\",\n  sum(bio) AS \"bio\",\n  sum(gas) AS \"gas\",\n  sum(lignite) AS \"lignite\",\n  sum(wind) AS \"wind\",\n  sum(solar) AS \"solar\"\nFROM generation\nWHERE\n  $__timeFilter(\"time\") AND\n  step = 'post_dayAhead'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Power Plant Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Generation $agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  agent AS metric,\n  sum(lignite) AS \"lignite\",\n  sum(gas) AS \"gas\",\n  sum(nuclear) AS \"nuclear\",\n  sum(coal) AS \"coal\",\n  sum(allocation) AS \"allocation\"\nFROM generation\nWHERE\n  $__timeFilter(\"time\") AND\n  step = 'post_dayAhead' AND\n  agent = '$agent'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Order Overview $agent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  max(price)*100 AS \"agent price\",\n  sum(volume) AS \"volume\"\nFROM orders\nWHERE\n  $__timeFilter(\"time\") AND\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  avg(price*100) AS \"market price\"\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Price Forecast",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  max(forecast) as \"max forecast\",\n  avg(forecast) AS \"average forecast\",\n  min(forecast) as \"min forcast\"\n  \nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  avg(forecast) AS \"agent forecast\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  max(price) AS \"actual_price\"\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(profit-emission-start_ups-fuel)/100\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(profit)/100 as \"Profit\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum((profit-emission-start_ups-fuel)/100) AS \"Revenue\",\n  sum(emission)/100 AS \"Emission Costs\",\n  sum(start_ups)/100 AS \"Starting Costs\",\n  sum(fuel)/100 AS \"Fuel Costs\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") AND\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(fuel)/100 as \"Fuel Costs\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(emission)/100 as \"Emission Costs\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  sum(start_ups)/100 as \"Starting Costs\"\nFROM cash_flows\nWHERE\n  $__timeFilter(\"time\") and\n  agent = '$agent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}