{
 "title": "dMAS",
 "description": "Dashboard of the distributed Multi-Agent-Simulation",
 "time": { "from": "2017-12-31T23:00:00.000Z", "to": "2018-01-31T23:00:00.000Z" },
 "panels": [
  {
   "title": "Market Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  volume\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Demand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(power) AS \"demand\"\nFROM demand\nWHERE\n  $__timeFilter(\"time\") AND\n  step = 'post_dayAhead'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Market Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  price\nFROM auction_results\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Weather Explorer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air) AS \"temp_air\",\n  avg(ghi) AS \"ghi\"\nFROM cosmo\nWHERE\n  $__timeFilter(\"time\") AND\n  country = 'DE'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(SQRT(POWER(wind_meridional,2)+POWER(wind_zonal,2))) AS \"wind_speed\"\nFROM cosmo\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Generation Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(bio) AS \"bio\",\n  sum(wind) AS \"wind\",\n  sum(solar) AS \"solar\",\n  sum(coal) AS \"coal\",\n  sum(lignite) AS \"lignite\",\n  sum(gas) AS \"gas\",\n  sum(water) AS \"water\",\n  sum(storage) AS \"storage\",\n  sum(nuclear) AS \"nuclear\"\nFROM capacities\nWHERE\n  $__timeFilter(\"time\") AND\n  agent NOT LIKE 'dem_de%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Generation Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(wind) AS \"wind\",\n  sum(nuclear) AS \"nuclear\",\n  sum(coal) AS \"coal\",\n  sum(solar) AS \"solar\",\n  sum(water) AS \"water\",\n  sum(bio) AS \"bio\",\n  sum(gas) AS \"gas\"\nFROM generation\nWHERE\n  $__timeFilter(\"time\") AND\n  step = 'optimize_dayAhead'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}