FROM python:3.9-slim

COPY ./requirements_.txt .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_pwp.txt
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN chown -R admin /src

COPY ./model/agents /src/agents

COPY ./model/apps /src/apps

COPY ./model/interfaces /src/interfaces

COPY ./model/aggregation ./src/aggregation

COPY ./model/systems ./src/systems

COPY ./model/data ./src/data

COPY ./model/main.py /src/main.py

USER admin
WORKDIR /src

CMD ["python", "-u" ,"./main.py"]