FROM python:3.9-slim

COPY ./requirements.txt .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_wtr.txt
# RUN pip install gurobi
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN chown -R admin /src

COPY ./model/agents /src/agents

COPY ./model/interfaces /src/interfaces

COPY ./model/data/Ref_GeoInfo.csv /src/data/Ref_GeoInfo.csv

COPY ./model/main.py /src/main.py

USER admin
WORKDIR /src

CMD ["python", "-u" ,"./main.py"]