FROM python:3.9-slim

COPY ./requirements/requirements_str.txt .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_str.txt
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN chown -R admin /src

COPY ./model/agent_service.cfg /src/agent_service.cfg

COPY ../model/agents/__init__.py /src/agents/__init__.py
COPY ../model/agents/basic_Agent.py /src/agents/basic_Agent.py
COPY ../model/agents/client_Agent.py /src/agents/client_Agent.py
COPY ../model/agents/str_Agent.py /src/agents/str_Agent.py

COPY ../model/apps /src/apps

COPY ../model/interfaces /src/interfaces

COPY ../model/aggregation ./src/aggregation

COPY ../model/components ./src/components

COPY ../model/data ./src/data

COPY ../model/main_str.py /src/main_str.py

USER admin
WORKDIR /src

CMD ["python", "./main_str.py"]