FROM python:3.9-slim

COPY ./requirements/requirements_wtr.txt .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_wtr.txt
# RUN pip install gurobi
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN chown -R admin /src

COPY ./model/agents/__init__.py /src/agents/__init__.py
COPY ./model/agents/basic_Agent.py /src/agents/basic_Agent.py
COPY ./model/agents/wtr_Agent.py /src/agents/wtr_Agent.py

COPY ./model/interfaces /src/interfaces

COPY ./model/data/Ref_GeoInfo.csv /src/data/Ref_GeoInfo.csv

COPY ./model/main_wtr.py /src/main_wtr.py

USER admin
WORKDIR /src

CMD ["python", "./main_wtr.py"]